import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const roboto = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} no-scrollbar `}>{children}</body>
    </html>
  );
}
